### ISSUE TITLE
DDPG+HER with images as input does not utilize GPU

### ISSUE THREAD

**Issue by JimLiu1213** [DLR-RM/stable-baselines3#511]
### Question

I am using DDPG+HER with images (64, 64, 4) and positions (3,1) as input, using rl-baselines3-zoo. I tried to reduce buffer size, but GPU is still not used. Also, is it possible to add those env_wrappers on Goal envs? Is it possible to make it easy to use on goal envs? 
My parameters:
```
FoodHuntingHSR-v1:
  <<: *pybullet-defaults
 # env_wrapper:
#    - gym.wrappers.resize_observation.ResizeObservation:
#        shape: 40
#    - gym.wrappers.gray_scale_observation.GrayScaleObservation:
#        keep_dim: true
  frame_stack: 4
  n_timesteps: !!float 1e6
  policy: 'MultiInputPolicy'
  batch_size: 128
  gamma: 0.98
  device: 'cuda'
  buffer_size: 20000
  learning_starts: 500
  noise_type: 'normal'
  noise_std: 0.1
  gradient_steps: 1
  train_freq: 1
  learning_rate: !!float 1e-3
  policy_kwargs: "dict(net_arch=[400,300])"
#, features_extractor_kwargs=dict(features_dim=256)
  replay_buffer_class: HerReplayBuffer
  replay_buffer_kwargs: "dict(n_sampled_goal=4, goal_selection_strategy='future', online_sampling=True, max_episode_length=100)"

```

### Additional context

Add any other context about the question here.

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
