### ISSUE TITLE
[Feature Request] DevOps Features

### ISSUE THREAD

**Issue by 09tangriro** [DLR-RM/stable-baselines3#545]
### 🚀 Feature

I think it would be cool to add a variety of DevOps features:

1. Pre commit hooks (e.g. black, isort). For example see below:
```
repos:
  - repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
    - id: black
      language_version: python3.8

  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.2
    hooks:
    - id: isort
      args: [--filter-files, --profile=black]
      files: \.py$
```
2. Introduce poetry https://python-poetry.org/ it's a really good dependency and packaging manager that replaces the setup.py script with its own automatic virtual environment handling. See an example toml spec below:
```
[tool.poetry]
name = "anvil"
version = "0.1.0"
description = "A library for rapid prototyping and testing of new ideas in RL."
authors = ["Rohan Tangri <rohan.tangri@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
pydantic = "^1.8.2"
torch = "^1.9.0"
numba = "^0.53.1"
numpy = "^1.21.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
flake8 = "^3.9.2"
black = "^21.7b0"
isort = "^5.9.2"
pre-commit = "^2.13.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

```
3. Add a script, something like setup_dev.sh, which can be run to setup development environment. See below for an example:
```
#!/bin/sh
echo ---------------------
echo Installing and creating poetry virtual environment
echo ---------------------
pip3 install poetry
poetry install
echo ""

echo ---------------------
echo Installing pre-commit hooks
echo ---------------------
pip3 install pre-commit
pre-commit install
echo ""

echo ---------------------
echo DONE
echo ---------------------
```

### Motivation

It would be nice to have a one-stop easy setup of the environment, and poetry has a lot of community support! (for reference, it's what we use at JP Morgan now).

### Alternatives

A clear and concise description of any alternative solutions or features you've considered, if any.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
